---
author: "Denis Fedorov"
title: "HW 2"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---
## Black Jack probabilities

Dear students in your second homework I want you to model Black Jack classic card game.

```{r}
deck <- read.csv("deck.csv")

origdeck <- deck[rep(seq_len(nrow(deck)), 4), ] #replicate 4 times
```

### Functions

```{r}
shuffle_deck <- function() { 
  deck <<- origdeck[sample(1:nrow(origdeck)),]
}

state <- function() {
  dealerSum <<- sum(dealer$value)
  cat("Dealer's hand:", fill = T)
  for (i in as.list(as.data.frame(t(dealer)))){
    cat("\t", i,"\n")
  }
  cat("sum", dealerSum, fill = T)
  cat("\n")
  
  youSum <<- sum(you$value)
  cat("Your hand:", fill = T)
  for (i in as.list(as.data.frame(t(you)))){
    cat("\t", i,"\n")
  }
  cat("sum", youSum, fill = T)
  cat("\n")
  
  if (youSum > 21) {
    cat("chances 0%")
    } 
  else if (dealerSum <= youSum) {
    cat("chances 100%")
    } 
  else {
    probab <<- sum(deck$value <= 21-youSum & deck$value >= dealerSum-youSum)/nrow(deck)
    cat("chances ", 100*probab, "%", sep="")
  }
  cat("\n--------------------\n\n\n")
    
}

start_game <- function() {
  deck <- shuffle_deck()
  
  dealer <<- deck[c(1,2),]
  deck <- deck[-c(1,2),]
  you <<- deck[c(1,2),]
  deck <<- deck[-c(1,2),]
  state()
}

deal <- function() {
  you <<- rbind(you, deck[1,])
  deck <<- deck[-1,]
  state()
}

stop_game <- function() {
  if (dealerSum <= youSum && youSum < 21) {
    cat(">>>Win<<<")
  }
  else {
    cat(">>>Loose<<<")
  }
}
```


### Example 1

```{r}
start_game()

deal()

stop_game()
```

### Example 2

```{r}
start_game()

while (youSum < dealerSum && youSum <= 21 && probab > 0.3){
  deal()
}
stop_game()
```

### Example 3

```{r}
start_game()

for (i in 1:3){
  deal()
}

stop_game()
```