---
author: "Denis Fedorov"
title: "HW 3"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---
```{r}
library(RIdeogram)
library(stringr)
```

```{r}
dg <- read.csv("DONGOLA_genes.tsv", sep='\t')
zg <- read.csv("ZANU_genes.tsv", sep='\t')
gm <- read.csv("gene_mapping.tsv", sep='\t')

#procesing DONG string and removing excessive info
gm <- cbind(gm,str_split_fixed(gm$DONG, "[,]", 5))
colnames(gm) <- seq(1:12)
gm <- gm[,-which(names(gm) %in% c("4","5","6","7","12"))]

colnames(gm) <- c('Zchr','Zmid','Zstrand','Dchr','Dmid','Dstrand','Dlen')
head(gm)
```


```{r}
karyotype_ZANU <- data.frame(
  c('X', 2, 3),
  c(1, 1, 1),
  c(27238055, 114783175, 97973315),
  c(229926, 969696, 969696),
  c('ZANU', 'ZANU', 'ZANU'),
  c(12, 12, 12),
  c(252525, 252525, 252525))
colnames(karyotype_ZANU) <- c('Chr','Start','End','fill','species','size','color')

karyotype_DONGOLA <- data.frame(
  c('X', 2, 3),
  c(1, 1, 1),
  c(26913133, 111988354, 95710210),
  c(229926, 969696, 969696),
  c('DONGOLA', 'DONGOLA', 'DONGOLA'),
  c(12, 12, 12),
  c(252525, 252525, 252525))
colnames(karyotype_DONGOLA) <- c('Chr','Start','End','fill','species','size','color')

karyotype_dual_comparison <- rbind(karyotype_ZANU, karyotype_DONGOLA)
head(karyotype_dual_comparison)

```

```{r}
gm[gm$Dchr == 'NC_053517.1', ]['Dchr'] = '2'
gm[gm$Dchr == 'NC_053518.1', ]['Dchr'] = '3'
gm[gm$Dchr == 'NC_053519.1', ]['Dchr'] = 'X'

#choosing only X, 2, 3
gm <- subset(gm, gm$Dchr %in% c('2', '3', 'X'))
gm <- subset(gm, gm$Zchr %in% c('2', '3', 'X'))
gm[gm$Dchr == 'X', ]['Dchr'] = '1'
gm[gm$Zchr == 'X', ]['Zchr'] = '1'
gm <- gm[gm$Zchr == gm$Dchr,]
gm$Dlen <- as.integer(gm$Dlen)
gm$Dmid <- as.integer(gm$Dmid)
gm$Dstrand <- as.integer(gm$Dstrand)
head(gm)

```
```{r}
#reversing 2 and 3
for(i in 1:nrow(gm)){
  row <- gm[i, ]
  if (row$Zchr == 2){
    gm[i, 'ZmidReverse'] <- 114783175 - row$Zmid
  }
  else if (row$Zchr == 3){
    gm[i, 'ZmidReverse'] <- 97973315 -row$Zmid
  }
  else {
    gm[i, 'ZmidReverse'] <- row$Zmid
  }
}

gm$chr1 <- as.numeric(gm$Zchr)
gm$str1 <- as.integer(gm$ZmidReverse - gm$Dlen/2)
gm$end1 <- as.integer(gm$ZmidReverse + gm$Dlen/2)
gm$chr2 <- as.numeric(gm$Dchr)
gm$str2 <- as.integer(gm$Dmid - gm$Dlen/2)
gm$end2 <- as.integer(gm$Dmid + gm$Dlen/2)

#coloring
for(i in 1:nrow(gm)){
  row <- gm[i, ]
  gm[i, 'fill'] <- ifelse(row$Zstrand == row$Dstrand, 'D88974', '74D87A')
}
gm <- gm[,-which(names(gm) %in% c('Zchr','Zmid','Zstrand','Dchr','Dmid','Dstrand','Dlen','ZmidReverse'))]
head(gm)
```

```{r eval=FALSE}
ideogram(karyotype = karyotype_dual_comparison, synteny = gm)
convertSVG("chromosome.svg", device = "png")

```





